# FROM -> direct the base image.
# FYI: https://hub.docker.com/u/nvidia
ARG BASE_IMAGE
FROM $BASE_IMAGE

ARG HTTP_PROXY

# setting proxy
# env
ENV HTTP_PROXY $HTTP_PROXY
ENV HTTPS_PROXY $HTTP_PROXY
ENV FTP_PROXY $HTTP_PROXY
ENV http_proxy $HTTP_PROXY
ENV https_proxy $HTTP_PROXY

# for Ubuntu (apt)
#RUN echo "Acquire::https::proxy \"$HTTP_PROXY\";" > /etc/apt/apt.conf.d/00-proxy
#RUN echo "Acquire::http::proxy  \"$HTTP_PROXY\";" >> /etc/apt/apt.conf.d/00-proxy
#RUN echo "Acquire::ftp::proxy  \"$HTTP_PROXY\";" >> /etc/apt/apt.conf.d/00-proxy

