# FROM -> direct the base image.
# FYI: https://hub.docker.com/u/nvidia
ARG BASE_IMAGE
FROM $BASE_IMAGE

#ARG HTTP_PROXY

# setting proxy
# env
#ENV HTTP_PROXY $HTTP_PROXY
#ENV HTTPS_PROXY $HTTP_PROXY
#ENV FTP_PROXY $HTTP_PROXY
#ENV http_proxy $HTTP_PROXY
#ENV https_proxy $HTTP_PROXY

#RUN echo "Acquire::https::proxy \"$HTTP_PROXY\";" > /etc/apt/apt.conf.d/00-proxy
#RUN echo "Acquire::http::proxy  \"$HTTP_PROXY\";" >> /etc/apt/apt.conf.d/00-proxy
#RUN echo "Acquire::ftp::proxy  \"$HTTP_PROXY\";" >> /etc/apt/apt.conf.d/00-proxy

# install standard tools
RUN apt-get update
#RUN apt-get -y install git

# if you have non-empty HTTP_PROXY value, decomment below.
# RUN git config --global http.proxy $HTTP_PROXY

# add what you need below.
RUN apt-get -y install python
RUN curl -kL https://bootstrap.pypa.io/get-pip.py | python
