apiVersion: v1
kind: List
items:
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: bonito-pvc-$BONITO_USER
  spec:
    accessModes:
      - ReadWriteMany
    storageClassName: bonito-base
    resources:
      requests:
        storage: $BONITO_VOLUME_SIZE
- kind: Pod
  apiVersion: v1
  metadata:
    name: bonito-$BONITO_USER.$BONITO_PROJECT-pod
  spec:
    volumes:
      - name: bonito-share
        persistentVolumeClaim:
          claimName: bonito-pvc-share
      - name: bonito-home
        persistentVolumeClaim:
          claimName: bonito-pvc-$BONITO_USER
    containers:
      - name: bonito-$BONITO_USER.$BONITO_PROJECT
        image: $BONITO_IMAGE
        ports:
          - containerPort: 8080
            name: "http-server"
        volumeMounts:
          - mountPath: "$BONITO_DIR"
            name: bonito-share
            subpath: share
          - mountPath: "/root/home"
            name: bonito-home
            subpath: home/$BONITO_USER
