apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: bonito-pv-$BONITO_USER
    labels:
      type: bonito-pv-volumes
  spec:
    storageClassName: bonito-$BONITO_USER
    capacity:
      storage: $BONITO_PV_HOME_SIZE
    accessModes:
      - ReadWriteMany
    hostPath:
      path: $BONITO_PV_HOME_DIR/$BONITO_USER
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: bonito-pvc-$BONITO_USER
  spec:
    accessModes:
      - ReadWriteMany
    storageClassName: bonito-$BONITO_USER
    resources:
      requests:
        storage: $BONITO_PV_HOME_SIZE
- kind: Pod
  apiVersion: v1
  metadata:
    name: bonito-$BONITO_USER-$BONITO_PROJECT-pod
  spec:
    volumes:
      - name: bonito-share
        persistentVolumeClaim:
          claimName: bonito-pvc-share
      - name: bonito-home
        persistentVolumeClaim:
          claimName: bonito-pvc-$BONITO_USER
    containers:
      - name: bonito-$BONITO_USER-$BONITO_PROJECT
        image: $BONITO_IMAGE
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
            name: "http-server"
        volumeMounts:
          - mountPath: "$BONITO_DIR"
            name: bonito-share
          - mountPath: "/root"
            name: bonito-home
