apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    tls.crt: "$BONITO_TMP_CERT_BASE64"
    tls.key: "$BONITO_TMP_KEY_BASE64"
  kind: Secret
  metadata:
    name: registry-tls.local-ssl
    namespace: $BONITO_NAMESPACE
  type: Opaque
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    name: registry
    namespace: $BONITO_NAMESPACE
  spec:
    replicas: 2
    template:
      metadata:
        labels:
          app: registry
      spec:
        volumes:
          - name: docker-data
            persistentVolumeClaim:
              claimName: bonito-pvc-regis
        containers:
        - name: registry
          image: registry:2
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
          volumeMounts:
          - name: docker-data
            mountPath: /var/lib/registry
- apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    name: registry-tls
    namespace: $BONITO_NAMESPACE
    annotations:
      kubernetes.io/ingress.class: "nginx"
      ingress.kubernetes.io/rewrite-target: /
  spec:
    tls:
    - secretName: registry-tls.local-ssl
    rules:
    - http:
        paths:
        - backend:
            serviceName: registry
            servicePort: 5000
          path: /
